# Configurations
title:            ALRCMt个人网站
longtitle:        主页
author:           ALRCMt
email:            b122330417@163.com
description: >
  ALRCMt 的个人网站，记录服务器、虚拟化、软路由、嵌入式、Jekyll 博客搭建与日常技术折腾的学习笔记、教程和个人介绍。

timezone:         Asia/Shanghai

version:          1.0
gitbook_version:  3.2.3

url:              'https://ht.tyyz2415.top'
baseurl:          ''
rss:              RSS
lang:             'zh-CN'

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     ./images/fav.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: magritte

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts
  - Gemfile.lock
  - _site
  - node_modules
  - vendor


collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

comments:
  provider: "giscus"
  giscus:
    repo: "ALRCMt/ALRCMt.github.io"              # 你的 GitHub 仓库名
    repo_id: "R_kgDOPvgepA"                                  # 可选：从 giscus 配置页获得，如果使用 repo 名可留空
    category_name: "Comments"                    # 你刚才创建的 Discussion 分类名
    category_id: "DIC_kwDOPvgepM4C9O3h"                     # 从 giscus 配置页获得
    mapping: "pathname"                          # 映射方式，可选 pathname、url、title 等
    strict: 0
    reactions_enabled: 1
    emit_metadata: 0
    input_position: "top"
    theme: "preferred_color_scheme"
    lang: "zh-CN"

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
